services:
  # 1. microservicio de NestJS
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-container
    ports:
      - '${PORT_HOST}:${PORT_CONTENEDOR}'
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV}
    depends_on:
      - auth-db # Espera a que la base de datos esté lista antes de arrancar

  # 2. motor de Base de Datos MySQL (Aislado de tu XAMPP local)
  auth-db:
    image: mysql:8.0
    container_name: auth-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - '3307:3306' # Expuesto en el 3307 para no pelear con tu PC
    volumes:
      - mysql-data:/var/lib/mysql # Guarda los datos para que sean persistentes

  # 3. panel de control visual para la base de datos
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: auth-phpmyadmin
    environment:
      PMA_HOST: auth-db
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
    ports:
      - '8080:80' # Tu puerta de entrada visual
    depends_on:
      - auth-db

# El espacio en tu disco duro reservado para que los usuarios no se borren
volumes:
  mysql-data:
